### ISSUE TITLE
Build error: arguments to `krun_set_exec` are incorrect

### ISSUE THREAD

**Issue by marco-04** [AsahiLinux/krun#62]
I'm having this build error on Gentoo with rust-bin 1.80.1 and bindgen 0.69.4

```
error[E0308]: arguments to this function are incorrect
   --> crates/krun/src/bin/krun.rs:327:13
    |
327 |             krun_set_exec(
    |             ^^^^^^^^^^^^^
    |
note: types differ in mutability
   --> crates/krun/src/bin/krun.rs:330:17
    |
330 |                 krun_guest_args.as_ptr(),
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected raw pointer `*const *mut u8`
               found raw pointer `*const *const u8`
note: types differ in mutability
   --> crates/krun/src/bin/krun.rs:331:17
    |
331 |                 env.as_ptr(),
    |                 ^^^^^^^^^^^^
    = note: expected raw pointer `*const *mut u8`
               found raw pointer `*const *const u8`
note: function defined here
   --> /home/marcosti/.git_repos/krun/target/debug/build/krun-sys-fa48eabac47ff4f2/out/bindings.rs:510:12
    |
510 |     pub fn krun_set_exec(
    |            ^^^^^^^^^^^^^
```

Looking at the definitions of the `krun_guest_args` and `env` variables as `Vec<*const c_char>` it seems that it could be an issue with bindgen, tho I'm not sure. By manually changing the generated bindings, it builds and seems to work fine

**Comment by teohhanhui** [comment]
@marco-04 I thought it was fixed on `libkrun` side long ago: https://github.com/containers/libkrun/pull/181

**Comment by marco-04** [comment]
Unless it's on another branch, cloning the repo and building on main doesn't work for me

**Comment by marco-04** [comment]
I'm an idiot. For some reason I still had around an old libkrun.h header from a dirty installation. I got rid of it and now it works as expected. Thanks for the help!
